"""Adiciona campo last_alerted_at a Ingredient

Revision ID: 1312b7239e48
Revises: 1820073e6962
Create Date: 2025-09-01 13:40:58.082853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1312b7239e48'
down_revision = '1820073e6962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_alerted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.drop_column('last_alerted_at')

    # ### end Alembic commands ###
