"""Adiciona campo de modo de preparo a receitas

Revision ID: 1820073e6962
Revises: f0dddeb37f83
Create Date: 2025-08-31 14:33:41.399581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1820073e6962'
down_revision = 'f0dddeb37f83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preparation_steps', sa.Text(), nullable=True))
        batch_op.drop_column('ingredients_list')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredients_list', sa.VARCHAR(length=500), nullable=True))
        batch_op.drop_column('preparation_steps')

    # ### end Alembic commands ###
