"""Adiciona stripe_customer_id ao User

Revision ID: 73b98009d07a
Revises: ac9d5710bcc0
Create Date: 2025-08-28 04:03:07.798527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73b98009d07a'
down_revision = 'ac9d5710bcc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('stripe_customer_id')

    # ### end Alembic commands ###
