"""Implementa ficha técnica e histórico

Revision ID: e3178e2d8091
Revises: 223f1ced9f16
Create Date: 2025-08-31 00:22:41.129328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3178e2d8091'
down_revision = '223f1ced9f16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_used', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yield_quantity', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('yield_unit', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('total_weight_g', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('loss_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cost_per_serving', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('cost_per_serving')
        batch_op.drop_column('loss_percentage')
        batch_op.drop_column('total_weight_g')
        batch_op.drop_column('yield_unit')
        batch_op.drop_column('yield_quantity')

    op.drop_table('recipe_ingredient')
    op.drop_table('price_history')
    # ### end Alembic commands ###
