"""Adiciona campos de onboarding

Revision ID: f0dddeb37f83
Revises: e3178e2d8091
Create Date: 2025-08-31 00:40:45.637547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0dddeb37f83'
down_revision = 'e3178e2d8091'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onboarding_complete', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('has_created_ingredient', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('has_created_recipe', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('has_created_recipe')
        batch_op.drop_column('has_created_ingredient')
        batch_op.drop_column('onboarding_complete')

    # ### end Alembic commands ###
